// FIX: Added full content for constants.ts, defining TRANSLATIONS for English and Arabic.

export const TRANSLATIONS = {
  en: {
    chatHeader: 'Chat with Brainix',
    imageHeader: 'Image Generation',
    codeHeader: 'Code Generation',
    planHeader: 'Plan Generator',
    searchHeader: 'Web Search',
    contextualHeader: 'Contextual Q&A',
    adminHeader: 'Admin Panel',
    settings: 'Settings',
    language: 'Language',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    save: 'Save',
    sendMessage: 'Send a message...',
    enterPromptHere: 'Enter your prompt here...',
    generating: 'Generating...',
    generate: 'Generate',
    searchTheWeb: 'Search the web...',
    sources: 'Sources',
    pasteTextContext: 'Paste your text context here...',
    or: 'OR',
    uploadAnImage: 'Drag & drop an image here, or click to select',
    askAQuestion: 'Ask a question based on the context...',
    welcomeTo: 'Welcome to',
    upgradeToPremium: 'Upgrade for 250 EGP/month',
    unlockFeatures: 'Your 3 daily free uses are over. Upgrade to unlock unlimited access.',
    enterActivationCode: 'Enter activation code',
    activate: 'Activate',
    invalidCode: 'Invalid or used code. Please try another one.',
    upgradeSuccess: 'Successfully upgraded! Your premium access is valid for one month.',
    premiumFeatures: 'Premium Features',
    feature1: 'Unlimited access to all modes',
    feature2: 'Priority support',
    feature3: 'Early access to new features',
    currentPlan: 'Current Plan',
    free: 'Free',
    premium: 'Premium',
    manageSubscription: 'Manage Subscription',
    activeUntil: 'Active until',
    customerSupport: 'Customer Support',
    dailyUsage: 'Daily Free Uses Remaining:',
    generateNewCode: 'Generate New Code',
    activationCodes: 'Activation Codes',
  },
  ar: {
    chatHeader: 'الدردشة مع Brainix',
    imageHeader: 'توليد الصور',
    codeHeader: 'توليد الأكواد',
    planHeader: 'مولد الخطط',
    searchHeader: 'بحث الويب',
    contextualHeader: 'سؤال وجواب سياقي',
    adminHeader: 'لوحة التحكم',
    settings: 'الإعدادات',
    language: 'اللغة',
    theme: 'المظهر',
    light: 'فاتح',
    dark: 'داكن',
    save: 'حفظ',
    sendMessage: 'أرسل رسالة...',
    enterPromptHere: 'أدخل طلبك هنا...',
    generating: 'جاري التوليد...',
    generate: 'توليد',
    searchTheWeb: 'ابحث في الويب...',
    sources: 'المصادر',
    pasteTextContext: 'ألصق النص السياقي هنا...',
    or: 'أو',
    uploadAnImage: 'اسحب وأفلت صورة هنا، أو انقر للاختيار',
    askAQuestion: 'اسأل سؤالاً بناءً على السياق...',
    welcomeTo: 'مرحباً بك في',
    upgradeToPremium: 'الترقية مقابل 250 جنيه شهريًا',
    unlockFeatures: 'لقد انتهت استخداماتك اليومية المجانية (3). قم بالترقية للحصول على وصول غير محدود.',
    activate: 'تفعيل',
    invalidCode: 'كود غير صالح أو مستخدم. يرجى تجربة كود آخر.',
    upgradeSuccess: 'تمت الترقية بنجاح! وصولك المميز صالح لمدة شهر واحد.',
    premiumFeatures: 'ميزات بريميوم',
    feature1: 'وصول غير محدود لجميع الأوضاع',
    feature2: 'دعم ذو أولوية',
    feature3: 'وصول مبكر للميزات الجديدة',
    currentPlan: 'الخطة الحالية',
    free: 'مجانية',
    premium: 'بريميوم',
    manageSubscription: 'إدارة الاشتراك',
    activeUntil: 'نشط حتى',
    customerSupport: 'خدمة العملاء',
    dailyUsage: 'الاستخدامات اليومية المجانية المتبقية:',
    generateNewCode: 'توليد كود جديد',
    activationCodes: 'أكواد التفعيل',
  },
};